#!/usr/bin/env Rscript
# generate_libraries_qmd.R
# Cross-platform script to generate a QMD file with all libraries used in .qmd files

cat("=== Generating Libraries QMD File ===\n\n")

# Get all .qmd files in current directory
qmd_files <- list.files(pattern = "\\.qmd$", ignore.case = TRUE)

if (length(qmd_files) == 0) {
  cat("❌ No .qmd files found in this folder.\n")
  cat("Press Enter to close...")
  readline()
  quit(save = "no", status = 1)
}

cat("Found", length(qmd_files), "QMD files:\n")
cat(paste("-", qmd_files, collapse = "\n"), "\n\n")

# Extract all library calls
libraries <- character(0)

for (file in qmd_files) {
  cat("Scanning:", file, "\n")
  content <- readLines(file, warn = FALSE)
  
  # Find lines starting with library(
  lib_lines <- grep("^library\\(", content, value = TRUE)
  
  # Extract library names
  lib_names <- gsub("^library\\(([^)]+)\\).*", "\\1", lib_lines)
  lib_names <- gsub('["\']', '', lib_names)  # Remove quotes
  lib_names <- trimws(lib_names)  # Remove whitespace
  
  libraries <- c(libraries, lib_names)
}

# Get unique sorted libraries
unique_libs <- unique(sort(libraries))
lib_count <- length(unique_libs)

cat("\n📊 Found", lib_count, "unique libraries\n")

# Create QMD content
qmd_content <- paste0('---
title: "Project Libraries Summary"
format: html
execute:
  eval: false
---

# Libraries Used in Project

The following `r ', lib_count, '` libraries are used across Quarto documents in this folder:

```{r}
#| echo: false
#| warning: false
#| message: false
')

# Add library calls
if (lib_count > 0) {
  lib_calls <- paste0("library(", unique_libs, ")", collapse = "\n")
  qmd_content <- paste0(qmd_content, lib_calls, "\n")
} else {
  qmd_content <- paste0(qmd_content, "# No libraries found\n")
}

qmd_content <- paste0(qmd_content, '```

**Generated on:** `r Sys.Date()`

> This file was automatically generated by scanning ', length(qmd_files), ' .qmd files in this folder.
')

# Write to file
output_file <- "project_libraries.qmd"
writeLines(qmd_content, output_file)

cat("✅ Generated:", output_file, "\n")
if (lib_count > 0) {
  cat("📚 Libraries:\n")
  cat(paste("-", unique_libs, collapse = "\n"), "\n")
}

cat("\nDone! Press Enter to close...")
invisible(readline())