project:
  type: website
  output-dir: docs

website:
  title: "inlabru workshop"
  navbar:
    left:
      - href: index.qmd
        text: Slides
      - href: about.qmd
        text: Practicals

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

