---
title: "`inlabru` Workshop"
author: "Jafet Belmont, Sara Martino and Janine Illian"
subtitle: "ICES 2025, Copenhagen"
filters: 
  - shinylive
---

# Welcome to the course!

-   Welcome to the `inlabu` workshop!
-   The goal for the workshop is to ...
-   The workshop is intended for ... No knowledge of `R-INLA` is required.
-   Workshop materials in the github repository [inlabru-workshop](https://github.com/Ecol-Stats/inlabru_workshop/tree/main/docs/copenague)

# Learning Objectives for the workshop

At the end of the workshop, participants will be able to:

-   ILO1
-   ILO2
-   ILO3, etc

Intended audience and level: The tutorial is intended for ... No knowledge of `R-INLA` is required.


# Schedule Program {#schedule-tabs}

::: panel-tabset
### Day 1

|     Time       |                   Topic                        | 
|:--------------:|:----------------------------------------------:|
| 10:00 - 11:00  |            ICES informative session            | 
| 10:30 - 11:30  |        **Session 1**: Introduction to `inlabru`| 
| 11:30 - 13:00  | [Practical Session 1](day1_practical.qmd)      | 
|  13:00 - 14:30 |                Lunch break                     | 
|  14:30 - 15:30 | **Session 2**: Bayesian inference & basics of INLA | 
|  15:30 - 15:45 |                Coffee Break                    | 
|  15:45 - 16:45 |            Practical Session 2                 | 
|  16:45 - 17:00 |               wrap-up and outlook              | 

: {.striped .hover}

### Day 2

|     Time       |                   Topic                             | 
|:--------------:|:---------------------------------------------------:|
|  9:00 - 10:00   |**Session 3**: Time models on a discrete domains    | 
|  10:00 - 10:30  |        Snack                                       | 
|  10:30 - 11:30  |**Session 4**: Time models on a continuous domains  | 
|  11:30 - 13:00 |                Practical Session 3                  | 
|  13:00 - 14:30 |                  Lunch break                        | 
|  14:30 - 15:30 |**Session 5**: Introduction to Spatial Statistics    | 
|  15:35 - 15:45 |            Coffee Break                             | 
|  15:45 - 16:45 |               Practical Session 4                   | 
|  16:45 - 17:00 |               wrap-up and outlook              | 

: {.striped .hover}

### Day 3

|     Time       |                   Topic                             | 
|:--------------:|:---------------------------------------------------:|
|  9:00 - 10:00   |**Session 6**: Areal Processes                      | 
|  10:00 - 10:30  |        Snack                                       | 
|  10:30 - 11:30  |**Session 7**: Geostatistics                        | 
|  11:30 - 13:00 |                Practical Session 5                  | 
|  13:00 - 14:30 |                  Lunch break                        | 
|  14:30 - 15:30 |**Session 8**: Spatial Point processes               | 
|  15:35 - 15:45 |            Coffee Break                             | 
|  15:45 - 16:45 |               Practical Session 6                   | 
|  16:45 - 17:00 |               wrap-up and outlook              | 

: {.striped .hover}


### Day 4

|     Time       |                   Topic                             | 
|:--------------:|:---------------------------------------------------:|
|  9:00 - 10:00   |**Session 9**: Spatiotemporal models                | 
|  10:00 - 10:30  |        Snack                                       | 
|  10:30 - 11:30  |**Session 10**: Multilikelihoods/joint likelihood   | 
|  11:30 - 13:00 |                Practical Session 7                  | 
|  13:00 - 14:30 |                  Lunch break                        | 
|  14:30 - 15:30 |**Session 11**: Non-linear models                     | 
|  15:35 - 15:45 |            Coffee Break                             | 
|  15:45 - 16:45 |               Practical Session 8                   | 
|  16:45 - 17:00 |               wrap-up and outlook              | 

: {.striped .hover}


### Day 5

|     Time       |                   Topic                             | 
|:--------------:|:---------------------------------------------------:|
|  9:00 - 10:00   |**Session 12**: Complex observational processes: Zero inflated models| 
|  10:00 - 10:30  |        Snack                                       | 
|  10:30 - 11:30  |**Session 13**: Complex observational processes: Thinned point processes   | 
|  11:30 - 13:00 |                Practical Session 9                  | 
|  13:00 - 13:15 |                  Coffee Break                         | 
|  13:15 - 14:00 |  Closing session                             | 

: {.striped .hover}

:::

# In preparation for the workshop

Participants are required to follow the next steps before the day of the workshop:

1.  Install [R-INLA](https://www.r-inla.org/download-install)

2.  Install `inlabru` (available from CRAN)

3.  Make sure you have the latest `R-INLA`, `inlabru` and `R` versions installed.
